version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: jculley
      POSTGRES_PASSWORD: 931012jC
      POSTGRES_DB: textstorage
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://jculley:931012jC@db/textstorage
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
volumes:
  postgres_data:
