"""Added definition to Keyword

Revision ID: 2ef9d9879333
Revises: 8a7440a086f4
Create Date: 2024-02-09 19:03:29.419714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef9d9879333'
down_revision = '8a7440a086f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('definition', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('definition')

    # ### end Alembic commands ###
