"""empty message

Revision ID: 3aaf65d5632d
Revises: 2ef9d9879333
Create Date: 2024-02-11 15:51:46.153610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaf65d5632d'
down_revision = '2ef9d9879333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.alter_column('sentiment',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
