"""initial migration

Revision ID: 8a7440a086f4
Revises: 
Create Date: 2024-02-09 19:00:17.930144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7440a086f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'document', ['document_id'], ['id'])

    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
